### PR TITLE
Create EncryptAttributes::Attribute

### PR DESCRIPTION
**Pull request by camelmasa**
I tried to extract an`EncryptAttributes::Attribute` class from `EncryptAttributes` module for cleaner.
How is this :question:

### CODE REVIEW

**Comment by camelmasa** [comment]
@k2nr Could you review this when you have time 😃  🙇

**Comment by k2nr** [comment]
Change looks good, this is a simple refactoring without behavior change right? I guess this change is needed for other issues to be fixed, can you give me a link to the original issue?

**Comment by camelmasa** [comment]
@k2nr Thanks ! I shared on Slack 👍

**Comment by k2nr** [comment]
LGTM 👍

**Comment by camelmasa** [comment]
@k2nr Thanks for review 😄

**Pull request merged**
